### ISSUE TITLE
Code updation required | Object_Detection_on_Custom_Dataset.ipynb

### ISSUE THREAD

**Issue by SSusantAchary** [srivatsan88/YouTubeLI#2]
Present Error (file- GluonError-1) {Error potentially due  to 'dask' package }
![GluonError-1](https://user-images.githubusercontent.com/5210711/102693575-a5fc1280-4241-11eb-933f-3d1d28a7826b.JPG)

Changes required in code (file- GluonErrorSolved-2)
![GluonErrorSolved-2](https://user-images.githubusercontent.com/5210711/102693620-e9568100-4241-11eb-9d7e-ce07ec26fab5.JPG)

Source for the solution:
 (https://github.com/awslabs/autogluon/issues/818)

https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr#scrollTo=koIpPGxTSwav
![image](https://user-images.githubusercontent.com/5210711/102693894-c2994a00-4243-11eb-9f45-fe93a83dc281.png)

Thanks  
Susant

**Comment by srivatsan88** [comment]
Thanks Susant for pointing it out.. I think the packages of autogluon are restructured in new version of install. Will update the code in few weeks to work for new version and update

**Comment by SSusantAchary** [comment]
Thank you @srivatsan88  👍 .
